name: simulation
root: ./
startup_window: neighbors_topic
pre_window: export UAV_NAME=uav1; export RUN_TYPE=simulation; export UAV_TYPE=f450; export ODOMETRY_TYPE=gps; export WORLD_NAME=simulation
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - gazebo:
      layout: tiled
      panes:
        - waitForRos; roslaunch uvdar_core uvdar_gazebo.launch gui:=true
        - waitForOdometry; gz camera -c gzclient_camera -f uav1; history -s gz camera -c gzclient_camera -f uav1
  - status:
      layout: tiled
      synchronize: after
      panes:
        - export UAV_NAME=uav1; waitForSimulation; roslaunch mrs_uav_status status.launch
        - export UAV_NAME=uav2; waitForSimulation; roslaunch mrs_uav_status status.launch
        - export UAV_NAME=uav3; waitForSimulation; roslaunch mrs_uav_status status.launch
  - spawn:
      layout: even-vertical
      synchronize: after
      panes:
        - waitForSimulation; spawn_uav 1 --$UAV_TYPE --run --delete --file uav1_pos.yaml --enable-rangefinder --enable-ground-truth --enable-uv-camera --uv-camera-calibration-file "$HOME/mrs_workspace/src/uav_modules/ros_packages/uvdar_meta/uvdar_core/include/OCamCalib/config/calib_results_bf_uv_fe.txt" --enable-uv-leds --led-frequencies 6 6 --debug
        - waitForSimulation; spawn_uav 2 --$UAV_TYPE --run --delete --file uav2_pos.yaml --enable-rangefinder --enable-ground-truth --enable-uv-camera --uv-camera-calibration-file "$HOME/mrs_workspace/src/uav_modules/ros_packages/uvdar_meta/uvdar_core/include/OCamCalib/config/calib_results_bf_uv_fe.txt" --enable-uv-leds --led-frequencies 10 10 --debug
        - waitForSimulation; spawn_uav 3 --$UAV_TYPE --run --delete --file uav3_pos.yaml --enable-rangefinder --enable-ground-truth --enable-uv-camera --uv-camera-calibration-file "$HOME/mrs_workspace/src/uav_modules/ros_packages/uvdar_meta/uvdar_core/include/OCamCalib/config/calib_results_bf_uv_fe.txt" --enable-uv-leds --led-frequencies 15 15 --debug
  - control:
      layout: tiled
      synchronize: after
      panes:
        - export UAV_NAME=uav1; waitForSimulation; roslaunch mrs_uav_general core.launch config_mpc_tracker:=./custom_configs/mpc_tracker.yaml
        - export UAV_NAME=uav2; waitForSimulation; roslaunch mrs_uav_general core.launch config_mpc_tracker:=./custom_configs/mpc_tracker.yaml
        - export UAV_NAME=uav3; waitForSimulation; roslaunch mrs_uav_general core.launch config_mpc_tracker:=./custom_configs/mpc_tracker.yaml
  - automatic_start:
      layout: tiled
      synchronize: after
      panes:
        - export UAV_NAME=uav1; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
        - export UAV_NAME=uav2; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
        - export UAV_NAME=uav3; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
  - state_machine:
      layout: tiled
      synchronize: after
      panes:
        - waitForOdometry; history -s 'rosservice call /uav1/automatic_start/start'
        - waitForOdometry; history -s 'rosservice call /uav2/automatic_start/start'
        - waitForOdometry; history -s 'rosservice call /uav3/automatic_start/start'
  - command_sender:
      layout: tiled
      panes:
        - waitForSimulation; roslaunch flocking command_sender.launch
  - hover_mode:
      layout: tiled
      panes:
        - 'history -s rosservice call /command_sender/send_command \"value: 0\"'
  - swarming_mode:
      layout: tiled
      panes:
        - 'history -s rosservice call /command_sender/send_command \"value: 1\"'
  - emergency_mode:
      layout: tiled
      panes:
        - 'history -s rosservice call /command_sender/send_command \"value: 2\"'
  - takeoff:
      layout: tiled
      synchronize: after
      panes:
        # #{ uav1
        - 'export UAV_NAME=uav1;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
        # #{ uav2
        - 'export UAV_NAME=uav2;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
        # #{ uav3
        - 'export UAV_NAME=uav3;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
  - uv_observer:
      layout: even-vertical
      panes:
        - waitForCompile; gz world --pause=0; sleep 6;  export UAV_NAME=uav1; waitForControl; roslaunch uvdar_core multi_frequency_test.launch
        - waitForCompile; gz world --pause=0; sleep 6;  export UAV_NAME=uav2; waitForControl; roslaunch uvdar_core multi_frequency_test.launch
        - waitForCompile; gz world --pause=0; sleep 6;  export UAV_NAME=uav3; waitForControl; roslaunch uvdar_core multi_frequency_test.launch
  - kalman_filter:
      layout: even-vertical
      synchronize: after
      panes:
        - export UAV_NAME=uav1; waitForControl; roslaunch uvdar_core uvdar_kalman_identified.launch output_frame:=$UAV_NAME/stable_origin
        - export UAV_NAME=uav2; waitForControl; roslaunch uvdar_core uvdar_kalman_identified.launch output_frame:=$UAV_NAME/stable_origin
        - export UAV_NAME=uav3; waitForControl; roslaunch uvdar_core uvdar_kalman_identified.launch output_frame:=$UAV_NAME/stable_origin
  - slow_down:
      layout: even-vertical
      panes:
        - waitForSimulation; waitForRos; sleep 15; gz physics -u 100
  - sensor_neighbor:
      layout: tiled
      synchronize: after
      panes:
        - export UAV_NAME=uav1; waitForOdometry; roslaunch flocking sensor_neighbor.launch config_sensor_type:=./custom_configs/sensor_type.yaml
        - export UAV_NAME=uav2; waitForOdometry; roslaunch flocking sensor_neighbor.launch config_sensor_type:=./custom_configs/sensor_type.yaml
        - export UAV_NAME=uav3; waitForOdometry; roslaunch flocking sensor_neighbor.launch config_sensor_type:=./custom_configs/sensor_type.yaml
  - formation:
      layout: tiled
      synchronize: after
      panes:
        - export UAV_NAME=uav1; waitForOdometry; roslaunch flocking formation.launch config_flocking:=./custom_configs/flocking/modified.yaml
        - export UAV_NAME=uav2; waitForOdometry; roslaunch flocking formation.launch config_flocking:=./custom_configs/flocking/modified.yaml
        - export UAV_NAME=uav3; waitForOdometry; roslaunch flocking formation.launch config_flocking:=./custom_configs/flocking/modified.yaml
  - neighbors_topic:
      layout: tiled
      synchronize: after
      panes:
        - waitForRos; rostopic echo /uav1/sensor_neighbor/neighbors
        - waitForRos; rostopic echo /uav2/sensor_neighbor/neighbors
        - waitForRos; rostopic echo /uav3/sensor_neighbor/neighbors