frame: "gps_origin"

land_at_the_end: false

desired_height: 2.5 # [m] 

minimum_height: 2.0 # [m]

flocking:
  # Experiment parameters
  auto_start: false
  swarming_after_hover: 10 # [s]
  duration: 120 # [s]

  # Proximal control parameters
  proximal: 
    desired_distance: 6.0 # [m]
    range_multiplier: 1.8 
    steepness_potential: 2.0
    strength_potential: 6.0

  # Motion control parameters
  motion:
    K1: 0.5  # Linear gain
    K2: 0.2  # Angular gain
    K3: 0.1
    move_forward: 0.3 
    interpolate_coeff: 0.95
    fixed_heading: false 