name: simulation
root: ./
startup_window: hover_mode
pre_window: export UAV_NAME=uav1; export RUN_TYPE=simulation; export UAV_TYPE=f450; export ODOMETRY_TYPE=gps; export WORLD_NAME=simulation
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
  - gazebo:
      layout: tiled
      panes:
        - waitForRos; roslaunch mrs_simulation simulation.launch world_name:=grass_plane gui:=true
        - waitForOdometry; gz camera -c gzclient_camera -f uav1; history -s gz camera -c gzclient_camera -f uav1
  - status:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForSimulation; roslaunch mrs_uav_status status.launch
        - export UAV_NAME=uav2; waitForSimulation; roslaunch mrs_uav_status status.launch
        - export UAV_NAME=uav3; waitForSimulation; roslaunch mrs_uav_status status.launch
        - export UAV_NAME=uav4; waitForSimulation; roslaunch mrs_uav_status status.launch
  - spawn:
      layout: tiled
      panes:
        - waitForSimulation; spawn_uav 1 --file uav1_pos.txt --$UAV_TYPE --run --delete --enable-rangefinder --enable-ground-truth
        - waitForSimulation; spawn_uav 2 --file uav2_pos.txt --$UAV_TYPE --run --delete --enable-rangefinder --enable-ground-truth
        - waitForSimulation; spawn_uav 3 --file uav3_pos.txt --$UAV_TYPE --run --delete --enable-rangefinder --enable-ground-truth
        - waitForSimulation; spawn_uav 4 --file uav4_pos.txt --$UAV_TYPE --run --delete --enable-rangefinder --enable-ground-truth
  - control:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForSimulation; roslaunch mrs_uav_general core.launch config_mpc_tracker:=./custom_configs/mpc_tracker.yaml
        - export UAV_NAME=uav2; waitForSimulation; roslaunch mrs_uav_general core.launch config_mpc_tracker:=./custom_configs/mpc_tracker.yaml
        - export UAV_NAME=uav3; waitForSimulation; roslaunch mrs_uav_general core.launch config_mpc_tracker:=./custom_configs/mpc_tracker.yaml
        - export UAV_NAME=uav4; waitForSimulation; roslaunch mrs_uav_general core.launch config_mpc_tracker:=./custom_configs/mpc_tracker.yaml
  - automatic_start:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
        - export UAV_NAME=uav2; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
        - export UAV_NAME=uav3; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
        - export UAV_NAME=uav4; waitForSimulation; roslaunch mrs_uav_general automatic_start.launch
  - state_machine:
      layout: tiled
      panes:
        - waitForOdometry; history -s 'rosservice call /uav1/automatic_start/start'
        - waitForOdometry; history -s 'rosservice call /uav2/automatic_start/start'
        - waitForOdometry; history -s 'rosservice call /uav3/automatic_start/start'
        - waitForOdometry; history -s 'rosservice call /uav4/automatic_start/start'
  - takeoff:
      layout: tiled
      panes:
        # #{ uav1
        - 'export UAV_NAME=uav1;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
        # #{ uav2
        - 'export UAV_NAME=uav2;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
        # #{ uav3
        - 'export UAV_NAME=uav3;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
        # #{ uav4
        - 'export UAV_NAME=uav4;
          waitForControl;
          rosservice call /$UAV_NAME/mavros/cmd/arming 1;
          rosservice call /$UAV_NAME/mavros/set_mode 0 offboard'
        # #}
  - sensor_neighbor:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForOdometry; roslaunch flocking sensor_neighbor.launch config_uav_names:=./custom_configs/uav_names.yaml
        - export UAV_NAME=uav2; waitForOdometry; roslaunch flocking sensor_neighbor.launch config_uav_names:=./custom_configs/uav_names.yaml
        - export UAV_NAME=uav3; waitForOdometry; roslaunch flocking sensor_neighbor.launch config_uav_names:=./custom_configs/uav_names.yaml
        - export UAV_NAME=uav4; waitForOdometry; roslaunch flocking sensor_neighbor.launch config_uav_names:=./custom_configs/uav_names.yaml
  - formation:
      layout: tiled
      panes:
        - export UAV_NAME=uav1; waitForOdometry; roslaunch flocking formation.launch
        - export UAV_NAME=uav2; waitForOdometry; roslaunch flocking formation.launch
        - export UAV_NAME=uav3; waitForOdometry; roslaunch flocking formation.launch
        - export UAV_NAME=uav4; waitForOdometry; roslaunch flocking formation.launch
  - neighbors_topic:
      layout: tiled
      panes:
        - waitForRos; rostopic echo /uav1/sensor_neighbor/neighbors
        - waitForRos; rostopic echo /uav2/sensor_neighbor/neighbors
        - waitForRos; rostopic echo /uav3/sensor_neighbor/neighbors
        - waitForRos; rostopic echo /uav4/sensor_neighbor/neighbors
